### ISSUE TITLE
File ID mismatch

### ISSUE THREAD

**Issue by katerinabc** [katerinabc/developer_sna#2]
@mahdi-e 

Can you check the file ids ? If I  understand the data correctly, for each version, each file in the program is given a unique ID. 
For example the beginning of file-by-file for version 4 is this (Columns are: file from, file to, and number of dependencies from file_from to file_to).
 
1           8721      7
1          36927      5
1          58806      1
 1         122539      1
1         129404      5
52          22262      7

This means that in the developer-by-file file I should find the same file IDs than int he file-by-file for version 4. In this example I should find a file with ID 1, 52, 8721, 36927, 58806 etc.

I think there is a mismatch problem in the files or in my code. Focusing on version 4 (file-by-file_1.5.csv) I get these ID's at the end (ignore the first column, these are row numbers):
``{r}tail(task4)
      und_from_file_id und_to_file_id weight
16522           135895          24105     17
16523           135895          31287      8
16524           135895          54997      2
16525           135895          70539      5
16526           135895          96729      3
16527           135895         115874      3
``

which(dev4_raw$ID_File_und == 135895, c(1,3,6,43))
[1]  integer(0)
max(dev4_raw$ID_File_und, na.rm=T)
[1] 135268

**Comment by mahdi-e** [comment]
@katerinabc 

Hi.

I am almost sure that the the two IDs from the two files are the same. Specifically, as you could find in our prior communication:

" ... In the file "file-by-file.zip", variables “und_from_file_id” and “und_to_file_id” keeps unique identifier of the files in our dataset. Again, if a file exists in more than one version, it will have different identifier number in different versions.
... Also, please note that variables “und_from_file_id” and “und_to_file_id” in this file, correspond to the variable “ID_File_und” in the 2-model edge-list of developer-by-file."

One thing that might make you suspicious and is worthy to note is the following:
The file-to-file edgelist captures all of the interdependencies between files in a given software version. However, the developer-to-file dataset, records ONLY the cases where a developer conducts a task on a file (creation or modification). When most of the files inheriting from pervious version are left unchanged, you will see a lot of mismatches, when merging the two datasets; in the developer-to-file dataset you will see only the files that are changed or created in that specific version.

I hope this is clear now. Otherwise, please let me know.

**Comment by mahdi-e** [comment]
@katerinabc 

having said that, when I review the results, it also seem that there might be a problem with reading the CSV file. It would be nice if you could double-check your code for that.

**Comment by katerinabc** [comment]
I noticed than when I read all the files and crate the DF data set, most columns are read as strings . This is fixed now.
I reworked the complete script, but still get NA in the ownership network. 
I'm running these lines: 
`req_communication <- task4[,c(1:2)]`
`ownership_withid <- DF[ ,c(7, 43)] `
`req_communication[] <- ownership_withid$folder_owner[match(
  unlist(req_communication), ownership_withid$ID_File_und)]`

When I inspect the head of task4 and req_communication I'm expecting to see all the IDs replaced with names. But I get this: 
`head(task4)`
>  und_from_file_id und_to_file_id weight
1                1           8721      7
2                1          36927      5
3                1          58806      1
4                1         122539      1
5                1         129404      5
6               52          22262      7

`head(req_communication)`
 >und_from_file_id   und_to_file_id
1   chiara.moretti alessandro.basso
2   chiara.moretti             <NA>
3   chiara.moretti             <NA>
4   chiara.moretti             <NA>
5   chiara.moretti alessandro.basso
6             <NA>             <NA>`

I continue checking for the file-id 36927 in DF$ID_File_und (`which(DF$ID_File_und == 36927, )`), and get no results (`integer(0)`). The file id 36927 is hence not in the DF file. 

- Does this mean that the file id 36927 wasn't modified in version 4 of the software? It is listed as a file needed for version 4 to run, but it didn't need to be modified at this iteration? 

- Are all the file-ids unique to the version number ? This means that file id 36927 refers to a specific file in version 4 but the same file will have a different ID in version 5, 6, 7 etc ?

- If the file-ids are unique per version, and the file wasn't modified in version 4, there is no way to find out who owns the folder in which the file was stored ? 
If your answer to the 3 questions is _Yes_, would it make sense to  exclude these links between files ? We have a total of 27678 'na' in the required communication file. Or would you prefer it to replace it with something else. ?
